/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class nimbus_utils_CSet */

#ifndef _Included_nimbus_utils_CSet
#define _Included_nimbus_utils_CSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nimbus_utils_CSet
 * Method:    c_add
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_nimbus_utils_CSet_c_1add
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nimbus_utils_CSet
 * Method:    c_clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nimbus_utils_CSet_c_1clear
  (JNIEnv *, jobject);

/*
 * Class:     nimbus_utils_CSet
 * Method:    c_contains
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_nimbus_utils_CSet_c_1contains
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nimbus_utils_CSet
 * Method:    c_isEmpty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_nimbus_utils_CSet_c_1isEmpty
  (JNIEnv *, jobject);

/*
 * Class:     nimbus_utils_CSet
 * Method:    c_remove
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_nimbus_utils_CSet_c_1remove
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nimbus_utils_CSet
 * Method:    c_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nimbus_utils_CSet_c_1size
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
